const nacionalidades = [
  { nombre: 'Argentina', codigoPais: 'AR' },
  { nombre: 'Australia', codigoPais: 'AU' },
  { nombre: 'Austria', codigoPais: 'AT' },
  { nombre: 'Bélgica', codigoPais: 'BE' },
  { nombre: 'Brasil', codigoPais: 'BR' },
  { nombre: 'Canadá', codigoPais: 'CA' },
  { nombre: 'Chile', codigoPais: 'CL' },
  { nombre: 'China', codigoPais: 'CN' },
  { nombre: 'Colombia', codigoPais: 'CO' },
  { nombre: 'Corea del Sur', codigoPais: 'KR' },
  { nombre: 'Costa Rica', codigoPais: 'CR' },
  { nombre: 'Croacia', codigoPais: 'HR' },
  { nombre: 'Dinamarca', codigoPais: 'DK' },
  { nombre: 'Egipto', codigoPais: 'EG' },
  { nombre: 'España', codigoPais: 'ES' },
  { nombre: 'Estados Unidos', codigoPais: 'US' },
  { nombre: 'Finlandia', codigoPais: 'FI' },
  { nombre: 'Francia', codigoPais: 'FR' },
  { nombre: 'Grecia', codigoPais: 'GR' },
  { nombre: 'Holanda', codigoPais: 'NL' },
  { nombre: 'Honduras', codigoPais: 'HN' },
  { nombre: 'India', codigoPais: 'IN' },
  { nombre: 'Inglaterra', codigoPais: 'GB' },
  { nombre: 'Irlanda', codigoPais: 'IE' },
  { nombre: 'Italia', codigoPais: 'IT' },
  { nombre: 'Japón', codigoPais: 'JP' },
  { nombre: 'Marruecos', codigoPais: 'MA' },
  { nombre: 'México', codigoPais: 'MX' },
  { nombre: 'Noruega', codigoPais: 'NO' },
  { nombre: 'Nueva Zelanda', codigoPais: 'NZ' },
  { nombre: 'Panamá', codigoPais: 'PA' },
  { nombre: 'Paraguay', codigoPais: 'PY' },
  { nombre: 'Perú', codigoPais: 'PE' },
  { nombre: 'Polonia', codigoPais: 'PL' },
  { nombre: 'Portugal', codigoPais: 'PT' },
  { nombre: 'Rusia', codigoPais: 'RU' },
  { nombre: 'Suecia', codigoPais: 'SE' },
  { nombre: 'Suiza', codigoPais: 'CH' },
  { nombre: 'Tailandia', codigoPais: 'TH' },
  { nombre: 'Turquía', codigoPais: 'TR' },
  { nombre: 'Uruguay', codigoPais: 'UY' },
  { nombre: 'Venezuela', codigoPais: 'VE' },
  { nombre: 'Vietnam', codigoPais: 'VN' },
  { nombre: 'Zambia', codigoPais: 'ZM' },
  { nombre: 'Zimbabwe', codigoPais: 'ZW' },
  { nombre: 'Afganistán', codigoPais: 'AF' },
  { nombre: 'Albania', codigoPais: 'AL' },
  { nombre: 'Argelia', codigoPais: 'DZ' },
  { nombre: 'Armenia', codigoPais: 'AM' },
  { nombre: 'Azerbaiyán', codigoPais: 'AZ' },
  // Agrega más países y códigos según tus necesidades...
];

export default nacionalidades;
